/* auto-generated by OHOS-RS */
/* eslint-disable */

declare module 'librumqttc_ohos_example.so' {
  /** 获取 rumqttc 库版本信息 */
  export function getRumqttcVersion(): string

  export class MqttClient {
    /**
     * 构造函数：创建 MQTT 客户端并立即启动后台事件循环（自动连接）
     *
     * - brokerUrl: 完整的 broker URL（支持 tcp://, ws://, wss://）
     * - clientId: 客户端标识
     * - username / password: 可选认证信息
     * - keepAliveSecs: 心跳间隔（秒），默认 60
     * - cleanSession: 是否清除会话，默认 true
     */
    constructor(
      brokerUrl: string,
      clientId: string,
      username?: string | undefined | null,
      password?: string | undefined | null,
      keepAliveSecs?: number | undefined | null,
      cleanSession?: boolean | undefined | null
    )

    /** 检查客户端是否已连接到 broker */
    isConnected(): boolean

    /**
     * 订阅指定主题
     *
     * @param topic MQTT 主题（支持通配符 + 和 #）
     * @param qos 服务质量等级（0, 1, 2）
     */
    subscribe(topic: string, qos: number): boolean

    /** 取消订阅指定主题 */
    unsubscribe(topic: string): boolean

    /**
     * 发布消息到指定主题
     *
     * @param topic MQTT 主题
     * @param payload 消息内容（字符串）
     * @param qos 服务质量等级（0, 1, 2）
     * @param retain 是否保留消息
     */
    publish(topic: string, payload: string, qos: number, retain: boolean): boolean

    /** 主动断开与 broker 的连接 */
    disconnect(): boolean

    /**
     * 从事件队列中取出一条事件（JSON 字符串）
     *
     * 返回 null 表示队列为空
     */
    pollEvent(): string | null

    /** 一次性取出所有待处理事件（减少跨语言调用次数） */
    pollAllEvents(): Array<string>
  }
}
