# 使用 ohrs 编译 rumqttc OHOS NAPI 模块并复制到目标目录
Write-Host "开始使用 ohrs 编译 rumqttc-ohos-example..." -ForegroundColor Green

# 保存初始目录
$initialDir = Get-Location

# 切换到 Rust crate 目录（脚本所在目录）
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $scriptDir

# 清理之前的构建产物
Write-Host "清理目标目录..." -ForegroundColor Yellow
Remove-Item -Path "dist" -Recurse -Force -ErrorAction SilentlyContinue

# 使用 ohrs 构建所有架构
Write-Host "执行 ohrs build --release..." -ForegroundColor Yellow
ohrs build --release

if ($LASTEXITCODE -eq 0) {
    Write-Host "构建成功!" -ForegroundColor Green

    # 目标目录
    $libTargetBase = "libs"
    $typeTargetDir = "types"

    # 库文件名（与 Cargo.toml 中的 crate name 对应，连字符转下划线）
    $libName = "librumqttc_ohos_example.so"
    $typeTargetFile = "$typeTargetDir\$libName.d.ts"

    # 确保目标目录存在
    New-Item -ItemType Directory -Path "$libTargetBase\arm64-v8a" -Force | Out-Null
    New-Item -ItemType Directory -Path "$libTargetBase\armeabi-v7a" -Force | Out-Null
    New-Item -ItemType Directory -Path "$libTargetBase\x86_64" -Force | Out-Null
    New-Item -ItemType Directory -Path "$typeTargetDir" -Force | Out-Null

    # 复制各架构的库文件
    Write-Host "复制库文件..." -ForegroundColor Yellow
    $archMap = @{
        "arm64-v8a"   = "dist\arm64-v8a\$libName"
        "armeabi-v7a" = "dist\armeabi-v7a\$libName"
        "x86_64"      = "dist\x86_64\$libName"
    }

    foreach ($arch in $archMap.Keys) {
        $src = $archMap[$arch]
        if (Test-Path $src) {
            Copy-Item $src "$libTargetBase\$arch\" -Force
            Write-Host "  ✓ $arch" -ForegroundColor Cyan
        } else {
            Write-Host "  ✗ $arch (未找到: $src)" -ForegroundColor Red
        }
    }

    # 处理类型定义文件：将 index.d.ts 转换为 module 声明格式
    Write-Host "生成类型定义文件 (.d.ts)..." -ForegroundColor Yellow

    $indexDts = "dist\index.d.ts"
    if (Test-Path $indexDts) {
        # 读取生成的 index.d.ts 内容
        $indexContent = Get-Content $indexDts -Raw

        # 移除原始文件的注释头
        $indexContent = $indexContent -replace '(?s)/\* auto-generated by OHOS-RS \*/\s*/\* eslint-disable \*/\s*', ''

        # 将 "export declare" 改为 "export"，并添加缩进
        $moduleContent = $indexContent -replace '(?m)^export declare ', '  export '
        $moduleContent = $moduleContent -replace '(?m)^export class ', '  export class '
        $moduleContent = $moduleContent -replace '(?m)^  /\*\*', '    /**'
        $moduleContent = $moduleContent -replace '(?m)^    \*', '      *'
        $moduleContent = $moduleContent -replace '(?m)^  constructor', '    constructor'
        $moduleContent = $moduleContent -replace '(?m)^  (\w+)\(', '    $1('
        $moduleContent = $moduleContent -replace '(?m)^}$', '  }'

        # 生成最终的 .d.ts 文件
        $finalContent = @"
/* auto-generated by OHOS-RS */
/* eslint-disable */

declare module '$libName' {
$moduleContent}
"@

        # 写入文件
        $finalContent | Out-File -FilePath $typeTargetFile -Encoding utf8 -NoNewline

        Write-Host "  ✓ $typeTargetFile" -ForegroundColor Cyan
    } else {
        Write-Host "  ✗ 未找到 index.d.ts，跳过类型定义生成" -ForegroundColor Red
    }

    Write-Host "" -ForegroundColor White
    Write-Host "构建完成! 输出文件:" -ForegroundColor Green
    Write-Host "  - libs/arm64-v8a/$libName" -ForegroundColor Cyan
    Write-Host "  - libs/armeabi-v7a/$libName" -ForegroundColor Cyan
    Write-Host "  - libs/x86_64/$libName" -ForegroundColor Cyan
    Write-Host "  - $typeTargetFile" -ForegroundColor Cyan
} else {
    Write-Host "构建失败!" -ForegroundColor Red
    Set-Location $initialDir
    exit 1
}

# 返回初始目录
Set-Location $initialDir
